export const FETCH_DOGS_REQUEST = 'FETCH_DOGS_REQUEST';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOGS_FAILURE = 'FETCH_DOGS_FAILURE';

export const EDIT_DOG_REQUEST = 'EDIT_DOG_REQUEST';
export const EDIT_DOG_SUCCESS = 'EDIT_DOG_SUCCESS';
export const EDIT_DOG_FAILURE = 'EDIT_DOG_FAILURE';

export const ADD_DOG_REQUEST = 'ADD_DOG_REQUEST';
export const ADD_DOG_SUCCESS = 'ADD_DOG_SUCCESS';
export const ADD_DOG_FAILURE = 'ADD_DOG_FAILURE';

export const REMOVE_DOG_REQUEST = 'REMOVE_DOG_REQUEST';
export const REMOVE_DOG_SUCCESS = 'REMOVE_DOG_SUCCESS';
export const REMOVE_DOG_FAILURE = 'REMOVE_DOG_FAILURE';
