export const FETCH_TITLES_REQUEST = 'FETCH_TITLES_REQUEST';
export const FETCH_TITLES_SUCCESS = 'FETCH_TITLES_SUCCESS';
export const FETCH_TITLES_FAILURE = 'FETCH_TITLES_FAILURE';

export const SET_TITLE = 'SET_TITLE';
export const FETCH_TITLE_REQUEST = 'FETCH_TITLE_REQUEST';
export const FETCH_TITLE_SUCCESS = 'FETCH_TITLE_SUCCESS';
export const FETCH_TITLE_FAILURE = 'FETCH_TITLE_FAILURE';

export const EDIT_TITLE_REQUEST = 'EDIT_TITLE_REQUEST';
export const EDIT_TITLE_SUCCESS = 'EDIT_TITLE_SUCCESS';
export const EDIT_TITLE_FAILURE = 'EDIT_TITLE_FAILURE';

export const ADD_TITLE_REQUEST = 'ADD_TITLE_REQUEST';
export const ADD_TITLE_SUCCESS = 'ADD_TITLE_SUCCESS';
export const ADD_TITLE_FAILURE = 'ADD_TITLE_FAILURE';

export const REMOVE_TITLE_REQUEST = 'REMOVE_TITLE_REQUEST';
export const REMOVE_TITLE_SUCCESS = 'REMOVE_TITLE_SUCCESS';
export const REMOVE_TITLE_FAILURE = 'REMOVE_TITLE_FAILURE';
